# Includes another Makefile: see Makefile.pdlibbuilder

NAME = polybang

lib.name = $(NAME)
class.sources = $(NAME).c

# Extra/help files to include
datafiles = $(NAME)-help.pd $(NAME)-meta.pd README.md

PDLIBBUILDER_DIR=../pd-lib-builder/
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder